// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anchoring.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextReadyBatch = `-- name: ClaimNextReadyBatch :one
UPDATE merkle_batches
SET
    status = 'SUBMITTING',
    claimed_by = $1,
    claim_expires_at = NOW() + ($2::INT * INTERVAL '1 second'),
    chain_id = $3,
    contract_address = $4,
    updated_at = NOW()
WHERE id = (
    SELECT id FROM merkle_batches
    WHERE (status = 'READY' OR (status = 'SUBMITTING' AND claim_expires_at < NOW()))
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type ClaimNextReadyBatchParams struct {
	ClaimedBy       pgtype.Text `json:"claimed_by"`
	LeaseSeconds    int32       `json:"lease_seconds"`
	ChainID         pgtype.Int8 `json:"chain_id"`
	ContractAddress pgtype.Text `json:"contract_address"`
}

func (q *Queries) ClaimNextReadyBatch(ctx context.Context, arg ClaimNextReadyBatchParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, claimNextReadyBatch,
		arg.ClaimedBy,
		arg.LeaseSeconds,
		arg.ChainID,
		arg.ContractAddress,
	)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const commitNonceReservation = `-- name: CommitNonceReservation :one
UPDATE signer_nonce_reservations
SET
    status = 'COMMITTED',
    committed_at = NOW()
WHERE id = $1
  AND status = 'ACTIVE'
RETURNING id, batch_id, chain_id, signer_address, nonce, status, created_at, committed_at
`

func (q *Queries) CommitNonceReservation(ctx context.Context, id pgtype.UUID) (SignerNonceReservation, error) {
	row := q.db.QueryRow(ctx, commitNonceReservation, id)
	var i SignerNonceReservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ChainID,
		&i.SignerAddress,
		&i.Nonce,
		&i.Status,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const countMerkleBatches = `-- name: CountMerkleBatches :one
SELECT COUNT(*) FROM merkle_batches
`

func (q *Queries) CountMerkleBatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMerkleBatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBatchCertificate = `-- name: CreateBatchCertificate :one
INSERT INTO batch_certificates (
    batch_id, certificate_id, leaf_index, leaf_hash, proof_depth, public_id, document_hash
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
RETURNING id, batch_id, certificate_id, leaf_index, leaf_hash, proof_depth, public_id, document_hash, created_at
`

type CreateBatchCertificateParams struct {
	BatchID       pgtype.UUID `json:"batch_id"`
	CertificateID pgtype.UUID `json:"certificate_id"`
	LeafIndex     int32       `json:"leaf_index"`
	LeafHash      string      `json:"leaf_hash"`
	ProofDepth    int32       `json:"proof_depth"`
	PublicID      string      `json:"public_id"`
	DocumentHash  string      `json:"document_hash"`
}

func (q *Queries) CreateBatchCertificate(ctx context.Context, arg CreateBatchCertificateParams) (BatchCertificate, error) {
	row := q.db.QueryRow(ctx, createBatchCertificate,
		arg.BatchID,
		arg.CertificateID,
		arg.LeafIndex,
		arg.LeafHash,
		arg.ProofDepth,
		arg.PublicID,
		arg.DocumentHash,
	)
	var i BatchCertificate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CertificateID,
		&i.LeafIndex,
		&i.LeafHash,
		&i.ProofDepth,
		&i.PublicID,
		&i.DocumentHash,
		&i.CreatedAt,
	)
	return i, err
}

const createBatchCertificateProofNode = `-- name: CreateBatchCertificateProofNode :one

INSERT INTO batch_certificate_proof_nodes (
    batch_certificate_id, proof_index, sibling_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, batch_certificate_id, proof_index, sibling_hash, created_at
`

type CreateBatchCertificateProofNodeParams struct {
	BatchCertificateID pgtype.UUID `json:"batch_certificate_id"`
	ProofIndex         int32       `json:"proof_index"`
	SiblingHash        string      `json:"sibling_hash"`
}

// ============================================================================
// 3. PROOF NODES QUERIES
// ============================================================================
func (q *Queries) CreateBatchCertificateProofNode(ctx context.Context, arg CreateBatchCertificateProofNodeParams) (BatchCertificateProofNode, error) {
	row := q.db.QueryRow(ctx, createBatchCertificateProofNode, arg.BatchCertificateID, arg.ProofIndex, arg.SiblingHash)
	var i BatchCertificateProofNode
	err := row.Scan(
		&i.ID,
		&i.BatchCertificateID,
		&i.ProofIndex,
		&i.SiblingHash,
		&i.CreatedAt,
	)
	return i, err
}

const createBlockchainTransaction = `-- name: CreateBlockchainTransaction :one

INSERT INTO blockchain_transactions (
    batch_id, nonce_reservation_id, replacement_sequence, chain_id,
    from_address, to_address, nonce, transaction_type, value_wei,
    calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei,
    tx_hash, status, replaces_transaction_id, prepared_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, 'PREPARED',
    $15, NOW()
)
RETURNING id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at
`

type CreateBlockchainTransactionParams struct {
	BatchID                 pgtype.UUID    `json:"batch_id"`
	NonceReservationID      pgtype.UUID    `json:"nonce_reservation_id"`
	ReplacementSequence     int32          `json:"replacement_sequence"`
	ChainID                 int64          `json:"chain_id"`
	FromAddress             string         `json:"from_address"`
	ToAddress               string         `json:"to_address"`
	Nonce                   int64          `json:"nonce"`
	TransactionType         int32          `json:"transaction_type"`
	ValueWei                pgtype.Numeric `json:"value_wei"`
	Calldata                []byte         `json:"calldata"`
	GasLimit                int64          `json:"gas_limit"`
	MaxFeePerGasWei         pgtype.Numeric `json:"max_fee_per_gas_wei"`
	MaxPriorityFeePerGasWei pgtype.Numeric `json:"max_priority_fee_per_gas_wei"`
	TxHash                  string         `json:"tx_hash"`
	ReplacesTransactionID   pgtype.UUID    `json:"replaces_transaction_id"`
}

// ============================================================================
// 5. BLOCKCHAIN TRANSACTION ATTEMPT QUERIES
// ============================================================================
func (q *Queries) CreateBlockchainTransaction(ctx context.Context, arg CreateBlockchainTransactionParams) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, createBlockchainTransaction,
		arg.BatchID,
		arg.NonceReservationID,
		arg.ReplacementSequence,
		arg.ChainID,
		arg.FromAddress,
		arg.ToAddress,
		arg.Nonce,
		arg.TransactionType,
		arg.ValueWei,
		arg.Calldata,
		arg.GasLimit,
		arg.MaxFeePerGasWei,
		arg.MaxPriorityFeePerGasWei,
		arg.TxHash,
		arg.ReplacesTransactionID,
	)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const createMerkleBatch = `-- name: CreateMerkleBatch :one


INSERT INTO merkle_batches (
    canonical_batch_id, tree_algorithm, tree_version,
    leaf_encoding_version, proof_format_version, status
) VALUES (
    $1, $2, $3,
    $4, $5, 'BUILDING'
)
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type CreateMerkleBatchParams struct {
	CanonicalBatchID    string `json:"canonical_batch_id"`
	TreeAlgorithm       string `json:"tree_algorithm"`
	TreeVersion         int32  `json:"tree_version"`
	LeafEncodingVersion string `json:"leaf_encoding_version"`
	ProofFormatVersion  string `json:"proof_format_version"`
}

// ============================================================================
// Anchoring Domain sqlc Queries (Phase 5B)
// ============================================================================
// ============================================================================
// 1. MERKLE BATCH QUERIES
// ============================================================================
func (q *Queries) CreateMerkleBatch(ctx context.Context, arg CreateMerkleBatchParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, createMerkleBatch,
		arg.CanonicalBatchID,
		arg.TreeAlgorithm,
		arg.TreeVersion,
		arg.LeafEncodingVersion,
		arg.ProofFormatVersion,
	)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const extendBatchClaim = `-- name: ExtendBatchClaim :one
UPDATE merkle_batches
SET
    claim_expires_at = NOW() + ($1::INT * INTERVAL '1 second'),
    updated_at = NOW()
WHERE id = $2
  AND status = 'SUBMITTING'
  AND claimed_by = $3
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type ExtendBatchClaimParams struct {
	LeaseSeconds int32       `json:"lease_seconds"`
	ID           pgtype.UUID `json:"id"`
	ClaimedBy    pgtype.Text `json:"claimed_by"`
}

func (q *Queries) ExtendBatchClaim(ctx context.Context, arg ExtendBatchClaimParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, extendBatchClaim, arg.LeaseSeconds, arg.ID, arg.ClaimedBy)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const finalizeBatchTree = `-- name: FinalizeBatchTree :one
UPDATE merkle_batches
SET
    merkle_root = $1,
    leaf_count = $2,
    status = 'READY',
    ready_at = NOW(),
    updated_at = NOW()
WHERE id = $3
  AND status = 'BUILDING'
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type FinalizeBatchTreeParams struct {
	MerkleRoot pgtype.Text `json:"merkle_root"`
	LeafCount  int32       `json:"leaf_count"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) FinalizeBatchTree(ctx context.Context, arg FinalizeBatchTreeParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, finalizeBatchTree, arg.MerkleRoot, arg.LeafCount, arg.ID)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const findEligibleCertificatesForBatch = `-- name: FindEligibleCertificatesForBatch :many

SELECT c.id, c.public_id, c.document_hash, c.status
FROM certificates c
LEFT JOIN batch_certificates bc ON bc.certificate_id = c.id
WHERE bc.id IS NULL
  AND c.status IN ('ISSUED', 'REVOKED', 'REPLACED')
  AND c.document_hash IS NOT NULL
ORDER BY c.created_at ASC
LIMIT $1
`

type FindEligibleCertificatesForBatchRow struct {
	ID           pgtype.UUID `json:"id"`
	PublicID     string      `json:"public_id"`
	DocumentHash pgtype.Text `json:"document_hash"`
	Status       string      `json:"status"`
}

// ============================================================================
// 2. BATCH CERTIFICATES QUERIES
// ============================================================================
func (q *Queries) FindEligibleCertificatesForBatch(ctx context.Context, limit int32) ([]FindEligibleCertificatesForBatchRow, error) {
	rows, err := q.db.Query(ctx, findEligibleCertificatesForBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindEligibleCertificatesForBatchRow
	for rows.Next() {
		var i FindEligibleCertificatesForBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.DocumentHash,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveNonceReservationByBatchID = `-- name: GetActiveNonceReservationByBatchID :one
SELECT id, batch_id, chain_id, signer_address, nonce, status, created_at, committed_at FROM signer_nonce_reservations
WHERE batch_id = $1
  AND status = 'ACTIVE'
LIMIT 1
`

func (q *Queries) GetActiveNonceReservationByBatchID(ctx context.Context, batchID pgtype.UUID) (SignerNonceReservation, error) {
	row := q.db.QueryRow(ctx, getActiveNonceReservationByBatchID, batchID)
	var i SignerNonceReservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ChainID,
		&i.SignerAddress,
		&i.Nonce,
		&i.Status,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getActiveTransactionByReservationID = `-- name: GetActiveTransactionByReservationID :one
SELECT id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at FROM blockchain_transactions
WHERE nonce_reservation_id = $1
  AND status IN ('PREPARED', 'BROADCAST')
LIMIT 1
`

func (q *Queries) GetActiveTransactionByReservationID(ctx context.Context, nonceReservationID pgtype.UUID) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, getActiveTransactionByReservationID, nonceReservationID)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const getAuthoritativeTransactionForBatch = `-- name: GetAuthoritativeTransactionForBatch :one
SELECT bt.id, bt.batch_id, bt.nonce_reservation_id, bt.replacement_sequence, bt.chain_id, bt.from_address, bt.to_address, bt.nonce, bt.transaction_type, bt.value_wei, bt.calldata, bt.gas_limit, bt.max_fee_per_gas_wei, bt.max_priority_fee_per_gas_wei, bt.tx_hash, bt.status, bt.block_number, bt.block_hash, bt.gas_used, bt.replaces_transaction_id, bt.failure_code, bt.failure_detail_code, bt.prepared_at, bt.broadcast_at, bt.mined_at, bt.replaced_at, bt.failed_at
FROM blockchain_transactions bt
JOIN merkle_batches mb ON mb.authoritative_transaction_id = bt.id
WHERE mb.id = $1
`

func (q *Queries) GetAuthoritativeTransactionForBatch(ctx context.Context, batchID pgtype.UUID) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, getAuthoritativeTransactionForBatch, batchID)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const getBatchCertificateByCertID = `-- name: GetBatchCertificateByCertID :one
SELECT id, batch_id, certificate_id, leaf_index, leaf_hash, proof_depth, public_id, document_hash, created_at FROM batch_certificates
WHERE certificate_id = $1
`

func (q *Queries) GetBatchCertificateByCertID(ctx context.Context, certificateID pgtype.UUID) (BatchCertificate, error) {
	row := q.db.QueryRow(ctx, getBatchCertificateByCertID, certificateID)
	var i BatchCertificate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CertificateID,
		&i.LeafIndex,
		&i.LeafHash,
		&i.ProofDepth,
		&i.PublicID,
		&i.DocumentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getBatchCertificateByID = `-- name: GetBatchCertificateByID :one
SELECT id, batch_id, certificate_id, leaf_index, leaf_hash, proof_depth, public_id, document_hash, created_at FROM batch_certificates
WHERE id = $1
`

func (q *Queries) GetBatchCertificateByID(ctx context.Context, id pgtype.UUID) (BatchCertificate, error) {
	row := q.db.QueryRow(ctx, getBatchCertificateByID, id)
	var i BatchCertificate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CertificateID,
		&i.LeafIndex,
		&i.LeafHash,
		&i.ProofDepth,
		&i.PublicID,
		&i.DocumentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getBatchCertificateByPublicID = `-- name: GetBatchCertificateByPublicID :one
SELECT id, batch_id, certificate_id, leaf_index, leaf_hash, proof_depth, public_id, document_hash, created_at FROM batch_certificates
WHERE public_id = $1
`

func (q *Queries) GetBatchCertificateByPublicID(ctx context.Context, publicID string) (BatchCertificate, error) {
	row := q.db.QueryRow(ctx, getBatchCertificateByPublicID, publicID)
	var i BatchCertificate
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.CertificateID,
		&i.LeafIndex,
		&i.LeafHash,
		&i.ProofDepth,
		&i.PublicID,
		&i.DocumentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockchainTransactionByHash = `-- name: GetBlockchainTransactionByHash :one
SELECT id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at FROM blockchain_transactions
WHERE tx_hash = $1
`

func (q *Queries) GetBlockchainTransactionByHash(ctx context.Context, txHash string) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, getBlockchainTransactionByHash, txHash)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const getBlockchainTransactionByID = `-- name: GetBlockchainTransactionByID :one
SELECT id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at FROM blockchain_transactions
WHERE id = $1
`

func (q *Queries) GetBlockchainTransactionByID(ctx context.Context, id pgtype.UUID) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, getBlockchainTransactionByID, id)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const getHighestNonceBySigner = `-- name: GetHighestNonceBySigner :one
SELECT COALESCE(MAX(nonce), -1)::BIGINT AS max_nonce
FROM signer_nonce_reservations
WHERE chain_id = $1
  AND signer_address = $2
`

type GetHighestNonceBySignerParams struct {
	ChainID       int64  `json:"chain_id"`
	SignerAddress string `json:"signer_address"`
}

func (q *Queries) GetHighestNonceBySigner(ctx context.Context, arg GetHighestNonceBySignerParams) (int64, error) {
	row := q.db.QueryRow(ctx, getHighestNonceBySigner, arg.ChainID, arg.SignerAddress)
	var max_nonce int64
	err := row.Scan(&max_nonce)
	return max_nonce, err
}

const getMerkleBatchByCanonicalID = `-- name: GetMerkleBatchByCanonicalID :one
SELECT id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at FROM merkle_batches
WHERE canonical_batch_id = $1
`

func (q *Queries) GetMerkleBatchByCanonicalID(ctx context.Context, canonicalBatchID string) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, getMerkleBatchByCanonicalID, canonicalBatchID)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const getMerkleBatchByID = `-- name: GetMerkleBatchByID :one
SELECT id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at FROM merkle_batches
WHERE id = $1
`

func (q *Queries) GetMerkleBatchByID(ctx context.Context, id pgtype.UUID) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, getMerkleBatchByID, id)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const getMerkleBatchByNumber = `-- name: GetMerkleBatchByNumber :one
SELECT id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at FROM merkle_batches
WHERE batch_number = $1
`

func (q *Queries) GetMerkleBatchByNumber(ctx context.Context, batchNumber int64) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, getMerkleBatchByNumber, batchNumber)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const getNonceReservationByID = `-- name: GetNonceReservationByID :one
SELECT id, batch_id, chain_id, signer_address, nonce, status, created_at, committed_at FROM signer_nonce_reservations
WHERE id = $1
`

func (q *Queries) GetNonceReservationByID(ctx context.Context, id pgtype.UUID) (SignerNonceReservation, error) {
	row := q.db.QueryRow(ctx, getNonceReservationByID, id)
	var i SignerNonceReservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ChainID,
		&i.SignerAddress,
		&i.Nonce,
		&i.Status,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getProofNodesByBatchCertID = `-- name: GetProofNodesByBatchCertID :many
SELECT proof_index, sibling_hash
FROM batch_certificate_proof_nodes
WHERE batch_certificate_id = $1
ORDER BY proof_index ASC
`

type GetProofNodesByBatchCertIDRow struct {
	ProofIndex  int32  `json:"proof_index"`
	SiblingHash string `json:"sibling_hash"`
}

func (q *Queries) GetProofNodesByBatchCertID(ctx context.Context, batchCertificateID pgtype.UUID) ([]GetProofNodesByBatchCertIDRow, error) {
	rows, err := q.db.Query(ctx, getProofNodesByBatchCertID, batchCertificateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProofNodesByBatchCertIDRow
	for rows.Next() {
		var i GetProofNodesByBatchCertIDRow
		if err := rows.Scan(&i.ProofIndex, &i.SiblingHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBatchCertificatesByBatchID = `-- name: ListBatchCertificatesByBatchID :many
SELECT id, batch_id, certificate_id, leaf_index, leaf_hash, proof_depth, public_id, document_hash, created_at FROM batch_certificates
WHERE batch_id = $1
ORDER BY leaf_index ASC
`

func (q *Queries) ListBatchCertificatesByBatchID(ctx context.Context, batchID pgtype.UUID) ([]BatchCertificate, error) {
	rows, err := q.db.Query(ctx, listBatchCertificatesByBatchID, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchCertificate
	for rows.Next() {
		var i BatchCertificate
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.CertificateID,
			&i.LeafIndex,
			&i.LeafHash,
			&i.ProofDepth,
			&i.PublicID,
			&i.DocumentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerkleBatches = `-- name: ListMerkleBatches :many
SELECT id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at FROM merkle_batches
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListMerkleBatchesParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListMerkleBatches(ctx context.Context, arg ListMerkleBatchesParams) ([]MerkleBatch, error) {
	rows, err := q.db.Query(ctx, listMerkleBatches, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MerkleBatch
	for rows.Next() {
		var i MerkleBatch
		if err := rows.Scan(
			&i.ID,
			&i.BatchNumber,
			&i.CanonicalBatchID,
			&i.Status,
			&i.TreeAlgorithm,
			&i.TreeVersion,
			&i.LeafEncodingVersion,
			&i.ProofFormatVersion,
			&i.MerkleRoot,
			&i.LeafCount,
			&i.ClaimedBy,
			&i.ClaimExpiresAt,
			&i.AuthoritativeTransactionID,
			&i.ChainID,
			&i.ContractAddress,
			&i.BlockNumber,
			&i.BlockHash,
			&i.ConfirmationCount,
			&i.RetryCount,
			&i.FailureStage,
			&i.FailureCode,
			&i.FailureDetailCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadyAt,
			&i.SubmittedAt,
			&i.ConfirmedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByBatchID = `-- name: ListTransactionsByBatchID :many
SELECT id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at FROM blockchain_transactions
WHERE batch_id = $1
ORDER BY replacement_sequence ASC
`

func (q *Queries) ListTransactionsByBatchID(ctx context.Context, batchID pgtype.UUID) ([]BlockchainTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByBatchID, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockchainTransaction
	for rows.Next() {
		var i BlockchainTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.NonceReservationID,
			&i.ReplacementSequence,
			&i.ChainID,
			&i.FromAddress,
			&i.ToAddress,
			&i.Nonce,
			&i.TransactionType,
			&i.ValueWei,
			&i.Calldata,
			&i.GasLimit,
			&i.MaxFeePerGasWei,
			&i.MaxPriorityFeePerGasWei,
			&i.TxHash,
			&i.Status,
			&i.BlockNumber,
			&i.BlockHash,
			&i.GasUsed,
			&i.ReplacesTransactionID,
			&i.FailureCode,
			&i.FailureDetailCode,
			&i.PreparedAt,
			&i.BroadcastAt,
			&i.MinedAt,
			&i.ReplacedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBatchConfirmed = `-- name: MarkBatchConfirmed :one
UPDATE merkle_batches
SET
    status = 'CONFIRMED',
    block_number = $1,
    block_hash = $2,
    confirmation_count = $3,
    confirmed_at = NOW(),
    updated_at = NOW()
WHERE id = $4
  AND status = 'SUBMITTED'
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type MarkBatchConfirmedParams struct {
	BlockNumber       pgtype.Int8 `json:"block_number"`
	BlockHash         pgtype.Text `json:"block_hash"`
	ConfirmationCount int32       `json:"confirmation_count"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) MarkBatchConfirmed(ctx context.Context, arg MarkBatchConfirmedParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, markBatchConfirmed,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ConfirmationCount,
		arg.ID,
	)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const markBatchFailed = `-- name: MarkBatchFailed :one
UPDATE merkle_batches
SET
    status = 'FAILED',
    failure_stage = $1,
    failure_code = $2,
    failure_detail_code = $3,
    claimed_by = NULL,
    claim_expires_at = NULL,
    failed_at = NOW(),
    updated_at = NOW()
WHERE id = $4
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type MarkBatchFailedParams struct {
	FailureStage      pgtype.Text `json:"failure_stage"`
	FailureCode       pgtype.Text `json:"failure_code"`
	FailureDetailCode pgtype.Text `json:"failure_detail_code"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) MarkBatchFailed(ctx context.Context, arg MarkBatchFailedParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, markBatchFailed,
		arg.FailureStage,
		arg.FailureCode,
		arg.FailureDetailCode,
		arg.ID,
	)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const markBatchSubmitted = `-- name: MarkBatchSubmitted :one
UPDATE merkle_batches
SET
    status = 'SUBMITTED',
    claimed_by = NULL,
    claim_expires_at = NULL,
    submitted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'SUBMITTING'
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

func (q *Queries) MarkBatchSubmitted(ctx context.Context, id pgtype.UUID) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, markBatchSubmitted, id)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const markTransactionBroadcast = `-- name: MarkTransactionBroadcast :one
UPDATE blockchain_transactions
SET
    status = 'BROADCAST',
    broadcast_at = NOW()
WHERE id = $1
  AND status = 'PREPARED'
RETURNING id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at
`

func (q *Queries) MarkTransactionBroadcast(ctx context.Context, id pgtype.UUID) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionBroadcast, id)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const markTransactionFailed = `-- name: MarkTransactionFailed :one
UPDATE blockchain_transactions
SET
    status = 'FAILED',
    failure_code = $1,
    failure_detail_code = $2,
    failed_at = NOW()
WHERE id = $3
  AND status IN ('PREPARED', 'BROADCAST')
RETURNING id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at
`

type MarkTransactionFailedParams struct {
	FailureCode       pgtype.Text `json:"failure_code"`
	FailureDetailCode pgtype.Text `json:"failure_detail_code"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) MarkTransactionFailed(ctx context.Context, arg MarkTransactionFailedParams) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionFailed, arg.FailureCode, arg.FailureDetailCode, arg.ID)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const markTransactionMined = `-- name: MarkTransactionMined :one
UPDATE blockchain_transactions
SET
    status = 'MINED',
    block_number = $1,
    block_hash = $2,
    gas_used = $3,
    mined_at = NOW()
WHERE id = $4
  AND status = 'BROADCAST'
RETURNING id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at
`

type MarkTransactionMinedParams struct {
	BlockNumber pgtype.Int8 `json:"block_number"`
	BlockHash   pgtype.Text `json:"block_hash"`
	GasUsed     pgtype.Int8 `json:"gas_used"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkTransactionMined(ctx context.Context, arg MarkTransactionMinedParams) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionMined,
		arg.BlockNumber,
		arg.BlockHash,
		arg.GasUsed,
		arg.ID,
	)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const markTransactionReplaced = `-- name: MarkTransactionReplaced :one
UPDATE blockchain_transactions
SET
    status = 'REPLACED',
    replaced_at = NOW()
WHERE id = $1
  AND status IN ('PREPARED', 'BROADCAST')
RETURNING id, batch_id, nonce_reservation_id, replacement_sequence, chain_id, from_address, to_address, nonce, transaction_type, value_wei, calldata, gas_limit, max_fee_per_gas_wei, max_priority_fee_per_gas_wei, tx_hash, status, block_number, block_hash, gas_used, replaces_transaction_id, failure_code, failure_detail_code, prepared_at, broadcast_at, mined_at, replaced_at, failed_at
`

func (q *Queries) MarkTransactionReplaced(ctx context.Context, id pgtype.UUID) (BlockchainTransaction, error) {
	row := q.db.QueryRow(ctx, markTransactionReplaced, id)
	var i BlockchainTransaction
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.NonceReservationID,
		&i.ReplacementSequence,
		&i.ChainID,
		&i.FromAddress,
		&i.ToAddress,
		&i.Nonce,
		&i.TransactionType,
		&i.ValueWei,
		&i.Calldata,
		&i.GasLimit,
		&i.MaxFeePerGasWei,
		&i.MaxPriorityFeePerGasWei,
		&i.TxHash,
		&i.Status,
		&i.BlockNumber,
		&i.BlockHash,
		&i.GasUsed,
		&i.ReplacesTransactionID,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.PreparedAt,
		&i.BroadcastAt,
		&i.MinedAt,
		&i.ReplacedAt,
		&i.FailedAt,
	)
	return i, err
}

const releaseNonceReservation = `-- name: ReleaseNonceReservation :one
UPDATE signer_nonce_reservations
SET
    status = 'RELEASED'
WHERE id = $1
  AND status = 'ACTIVE'
RETURNING id, batch_id, chain_id, signer_address, nonce, status, created_at, committed_at
`

func (q *Queries) ReleaseNonceReservation(ctx context.Context, id pgtype.UUID) (SignerNonceReservation, error) {
	row := q.db.QueryRow(ctx, releaseNonceReservation, id)
	var i SignerNonceReservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ChainID,
		&i.SignerAddress,
		&i.Nonce,
		&i.Status,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const reserveSignerNonce = `-- name: ReserveSignerNonce :one

INSERT INTO signer_nonce_reservations (
    batch_id, chain_id, signer_address, nonce, status
) VALUES (
    $1, $2, $3,
    $4, 'ACTIVE'
)
RETURNING id, batch_id, chain_id, signer_address, nonce, status, created_at, committed_at
`

type ReserveSignerNonceParams struct {
	BatchID       pgtype.UUID `json:"batch_id"`
	ChainID       int64       `json:"chain_id"`
	SignerAddress string      `json:"signer_address"`
	Nonce         int64       `json:"nonce"`
}

// ============================================================================
// 4. SIGNER NONCE RESERVATION QUERIES
// ============================================================================
func (q *Queries) ReserveSignerNonce(ctx context.Context, arg ReserveSignerNonceParams) (SignerNonceReservation, error) {
	row := q.db.QueryRow(ctx, reserveSignerNonce,
		arg.BatchID,
		arg.ChainID,
		arg.SignerAddress,
		arg.Nonce,
	)
	var i SignerNonceReservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.ChainID,
		&i.SignerAddress,
		&i.Nonce,
		&i.Status,
		&i.CreatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const resetExpiredBatchClaim = `-- name: ResetExpiredBatchClaim :one
UPDATE merkle_batches
SET
    status = 'READY',
    claimed_by = NULL,
    claim_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status = 'SUBMITTING'
  AND claim_expires_at < NOW()
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

func (q *Queries) ResetExpiredBatchClaim(ctx context.Context, id pgtype.UUID) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, resetExpiredBatchClaim, id)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}

const setAuthoritativeTransaction = `-- name: SetAuthoritativeTransaction :one
UPDATE merkle_batches
SET
    authoritative_transaction_id = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, batch_number, canonical_batch_id, status, tree_algorithm, tree_version, leaf_encoding_version, proof_format_version, merkle_root, leaf_count, claimed_by, claim_expires_at, authoritative_transaction_id, chain_id, contract_address, block_number, block_hash, confirmation_count, retry_count, failure_stage, failure_code, failure_detail_code, created_at, updated_at, ready_at, submitted_at, confirmed_at, failed_at
`

type SetAuthoritativeTransactionParams struct {
	AuthoritativeTransactionID pgtype.UUID `json:"authoritative_transaction_id"`
	ID                         pgtype.UUID `json:"id"`
}

func (q *Queries) SetAuthoritativeTransaction(ctx context.Context, arg SetAuthoritativeTransactionParams) (MerkleBatch, error) {
	row := q.db.QueryRow(ctx, setAuthoritativeTransaction, arg.AuthoritativeTransactionID, arg.ID)
	var i MerkleBatch
	err := row.Scan(
		&i.ID,
		&i.BatchNumber,
		&i.CanonicalBatchID,
		&i.Status,
		&i.TreeAlgorithm,
		&i.TreeVersion,
		&i.LeafEncodingVersion,
		&i.ProofFormatVersion,
		&i.MerkleRoot,
		&i.LeafCount,
		&i.ClaimedBy,
		&i.ClaimExpiresAt,
		&i.AuthoritativeTransactionID,
		&i.ChainID,
		&i.ContractAddress,
		&i.BlockNumber,
		&i.BlockHash,
		&i.ConfirmationCount,
		&i.RetryCount,
		&i.FailureStage,
		&i.FailureCode,
		&i.FailureDetailCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.FailedAt,
	)
	return i, err
}
