// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    actor_user_id, target_organization_id, action, resource_type, resource_id, payload, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, actor_user_id, target_organization_id, action, resource_type, resource_id, payload, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	ActorUserID          pgtype.UUID `json:"actor_user_id"`
	TargetOrganizationID pgtype.UUID `json:"target_organization_id"`
	Action               string      `json:"action"`
	ResourceType         string      `json:"resource_type"`
	ResourceID           pgtype.UUID `json:"resource_id"`
	Payload              []byte      `json:"payload"`
	IpAddress            *netip.Addr `json:"ip_address"`
	UserAgent            pgtype.Text `json:"user_agent"`
}

// Immutable append-only audit event record.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ActorUserID,
		arg.TargetOrganizationID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Payload,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.TargetOrganizationID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Payload,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, actor_user_id, target_organization_id, action, resource_type, resource_id, payload, ip_address, user_agent, created_at
FROM audit_logs
WHERE actor_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor, arg.ActorUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TargetOrganizationID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Payload,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByOrg = `-- name: ListAuditLogsByOrg :many
SELECT id, actor_user_id, target_organization_id, action, resource_type, resource_id, payload, ip_address, user_agent, created_at
FROM audit_logs
WHERE target_organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByOrgParams struct {
	TargetOrganizationID pgtype.UUID `json:"target_organization_id"`
	Limit                int32       `json:"limit"`
	Offset               int32       `json:"offset"`
}

func (q *Queries) ListAuditLogsByOrg(ctx context.Context, arg ListAuditLogsByOrgParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByOrg, arg.TargetOrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.TargetOrganizationID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Payload,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
