// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (
    user_id, identity_type, identifier, credential_hash, metadata
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, identity_type, identifier, created_at, updated_at
`

type CreateAuthIdentityParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	IdentityType   string      `json:"identity_type"`
	Identifier     string      `json:"identifier"`
	CredentialHash pgtype.Text `json:"credential_hash"`
	Metadata       []byte      `json:"metadata"`
}

type CreateAuthIdentityRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	IdentityType string             `json:"identity_type"`
	Identifier   string             `json:"identifier"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (CreateAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity,
		arg.UserID,
		arg.IdentityType,
		arg.Identifier,
		arg.CredentialHash,
		arg.Metadata,
	)
	var i CreateAuthIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdentityType,
		&i.Identifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    user_id, token_hash, user_agent, ip_address, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, user_agent, ip_address, expires_at, created_at
`

type CreateAuthSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateAuthSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CreateAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAndRevokedSessions = `-- name: DeleteExpiredAndRevokedSessions :exec
DELETE FROM auth_sessions
WHERE expires_at < NOW() OR (revoked_at IS NOT NULL AND revoked_at < NOW() - INTERVAL '30 days')
`

func (q *Queries) DeleteExpiredAndRevokedSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAndRevokedSessions)
	return err
}

const getAuthIdentityForVerification = `-- name: GetAuthIdentityForVerification :one

SELECT id, user_id, identity_type, identifier, credential_hash, metadata, created_at, updated_at
FROM auth_identities
WHERE identity_type = $1 AND identifier = $2
`

type GetAuthIdentityForVerificationParams struct {
	IdentityType string `json:"identity_type"`
	Identifier   string `json:"identifier"`
}

// Provider Subject/Identifier Semantics:
// For EMAIL_PASSWORD: identifier is the user's normalized canonical lowercase email address.
// For GOOGLE_OAUTH: identifier is the immutable Google OAuth Subject ID ('sub' claim).
// Strictly internal query for password verification service; selects credential_hash.
func (q *Queries) GetAuthIdentityForVerification(ctx context.Context, arg GetAuthIdentityForVerificationParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityForVerification, arg.IdentityType, arg.Identifier)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdentityType,
		&i.Identifier,
		&i.CredentialHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionByHash = `-- name: GetAuthSessionByHash :one
SELECT id, user_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at
FROM auth_sessions
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetAuthSessionByHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserAuthIdentities = `-- name: ListUserAuthIdentities :many
SELECT id, user_id, identity_type, identifier, created_at, updated_at
FROM auth_identities
WHERE user_id = $1
ORDER BY created_at ASC
`

type ListUserAuthIdentitiesRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	IdentityType string             `json:"identity_type"`
	Identifier   string             `json:"identifier"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Public query for user profile/security settings; credential_hash is deliberately excluded.
func (q *Queries) ListUserAuthIdentities(ctx context.Context, userID pgtype.UUID) ([]ListUserAuthIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserAuthIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAuthIdentitiesRow
	for rows.Next() {
		var i ListUserAuthIdentitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IdentityType,
			&i.Identifier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, user_id, user_agent, ip_address, expires_at, revoked_at, created_at
FROM auth_sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListUserSessionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Excludes token_hash to prevent secret token leakage in session management views.
func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_sessions
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET revoked_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, id)
	return err
}
