// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCertificateFile = `-- name: AttachCertificateFile :one
UPDATE certificates
SET
    file_storage_key = $1,
    file_name = $2,
    file_size = $3,
    file_mime_type = $4,
    document_hash = $5,
    updated_at = NOW()
WHERE id = $6
  AND organization_id = $7
  AND status = 'DRAFT'
  AND deleted_at IS NULL
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type AttachCertificateFileParams struct {
	FileStorageKey pgtype.Text `json:"file_storage_key"`
	FileName       pgtype.Text `json:"file_name"`
	FileSize       pgtype.Int8 `json:"file_size"`
	FileMimeType   pgtype.Text `json:"file_mime_type"`
	DocumentHash   pgtype.Text `json:"document_hash"`
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) AttachCertificateFile(ctx context.Context, arg AttachCertificateFileParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, attachCertificateFile,
		arg.FileStorageKey,
		arg.FileName,
		arg.FileSize,
		arg.FileMimeType,
		arg.DocumentHash,
		arg.ID,
		arg.OrganizationID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const checkDocumentHashConflict = `-- name: CheckDocumentHashConflict :one
SELECT EXISTS (
    SELECT 1 FROM certificates
    WHERE document_hash = $1
      AND status IN ('ISSUED', 'REVOKED', 'REPLACED')
      AND deleted_at IS NULL
)
`

func (q *Queries) CheckDocumentHashConflict(ctx context.Context, documentHash pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkDocumentHashConflict, documentHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCertificatesByOrganization = `-- name: CountCertificatesByOrganization :one
SELECT COUNT(*) FROM certificates
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR recipient_email = LOWER($3))
  AND deleted_at IS NULL
`

type CountCertificatesByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Status         pgtype.Text `json:"status"`
	RecipientEmail pgtype.Text `json:"recipient_email"`
}

func (q *Queries) CountCertificatesByOrganization(ctx context.Context, arg CountCertificatesByOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificatesByOrganization, arg.OrganizationID, arg.Status, arg.RecipientEmail)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCertificatesByRecipient = `-- name: CountCertificatesByRecipient :one
SELECT COUNT(*) FROM certificates c
JOIN organizations o ON o.id = c.organization_id
WHERE c.recipient_user_id = $1
  AND c.status IN ('ISSUED', 'REVOKED', 'REPLACED')
  AND ($2::text IS NULL OR c.status = $2)
  AND c.deleted_at IS NULL
  AND o.deleted_at IS NULL
`

type CountCertificatesByRecipientParams struct {
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) CountCertificatesByRecipient(ctx context.Context, arg CountCertificatesByRecipientParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCertificatesByRecipient, arg.RecipientUserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertificateDraft = `-- name: CreateCertificateDraft :one

INSERT INTO certificates (
    public_id, organization_id, recipient_user_id, recipient_name, recipient_email,
    student_id_number, title, degree_type, major, grade_or_honors, graduation_date,
    issue_date, status, created_by_user_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, 'DRAFT', $13
)
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type CreateCertificateDraftParams struct {
	PublicID        string      `json:"public_id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	RecipientName   string      `json:"recipient_name"`
	RecipientEmail  string      `json:"recipient_email"`
	StudentIDNumber pgtype.Text `json:"student_id_number"`
	Title           string      `json:"title"`
	DegreeType      string      `json:"degree_type"`
	Major           pgtype.Text `json:"major"`
	GradeOrHonors   pgtype.Text `json:"grade_or_honors"`
	GraduationDate  pgtype.Date `json:"graduation_date"`
	IssueDate       pgtype.Date `json:"issue_date"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

// ============================================================================
// Certificates Domain sqlc Queries (Phase 5A)
// ============================================================================
func (q *Queries) CreateCertificateDraft(ctx context.Context, arg CreateCertificateDraftParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, createCertificateDraft,
		arg.PublicID,
		arg.OrganizationID,
		arg.RecipientUserID,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.StudentIDNumber,
		arg.Title,
		arg.DegreeType,
		arg.Major,
		arg.GradeOrHonors,
		arg.GraduationDate,
		arg.IssueDate,
		arg.CreatedByUserID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCertificateDraft = `-- name: DeleteCertificateDraft :one
UPDATE certificates
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
  AND status = 'DRAFT'
  AND deleted_at IS NULL
RETURNING id, file_storage_key
`

type DeleteCertificateDraftParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type DeleteCertificateDraftRow struct {
	ID             pgtype.UUID `json:"id"`
	FileStorageKey pgtype.Text `json:"file_storage_key"`
}

func (q *Queries) DeleteCertificateDraft(ctx context.Context, arg DeleteCertificateDraftParams) (DeleteCertificateDraftRow, error) {
	row := q.db.QueryRow(ctx, deleteCertificateDraft, arg.ID, arg.OrganizationID)
	var i DeleteCertificateDraftRow
	err := row.Scan(&i.ID, &i.FileStorageKey)
	return i, err
}

const getCertificateByID = `-- name: GetCertificateByID :one
SELECT id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at FROM certificates
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
`

type GetCertificateByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetCertificateByID(ctx context.Context, arg GetCertificateByIDParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByID, arg.ID, arg.OrganizationID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const getCertificateByIDForUpdate = `-- name: GetCertificateByIDForUpdate :one
SELECT id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at FROM certificates
WHERE id = $1
  AND organization_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type GetCertificateByIDForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetCertificateByIDForUpdate(ctx context.Context, arg GetCertificateByIDForUpdateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificateByIDForUpdate, arg.ID, arg.OrganizationID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const getCertificateByPublicID = `-- name: GetCertificateByPublicID :one
SELECT c.id, c.public_id, c.status, c.title, c.degree_type, c.major,
       c.graduation_date, c.issue_date, c.document_hash, c.revocation_reason_code,
       c.revoked_at, c.recipient_name,
       o.legal_name AS issuer_organization_name,
       o.official_domain AS issuer_organization_domain,
       o.country_code AS issuer_country_code,
       rep.public_id AS replaced_by_public_id
FROM certificates c
JOIN organizations o ON o.id = c.organization_id
LEFT JOIN certificates rep ON rep.id = c.replaced_by_certificate_id
WHERE c.public_id = $1
  AND c.status IN ('ISSUED', 'REVOKED', 'REPLACED')
  AND c.deleted_at IS NULL
  AND o.deleted_at IS NULL
`

type GetCertificateByPublicIDRow struct {
	ID                       pgtype.UUID        `json:"id"`
	PublicID                 string             `json:"public_id"`
	Status                   string             `json:"status"`
	Title                    string             `json:"title"`
	DegreeType               string             `json:"degree_type"`
	Major                    pgtype.Text        `json:"major"`
	GraduationDate           pgtype.Date        `json:"graduation_date"`
	IssueDate                pgtype.Date        `json:"issue_date"`
	DocumentHash             pgtype.Text        `json:"document_hash"`
	RevocationReasonCode     pgtype.Text        `json:"revocation_reason_code"`
	RevokedAt                pgtype.Timestamptz `json:"revoked_at"`
	RecipientName            string             `json:"recipient_name"`
	IssuerOrganizationName   string             `json:"issuer_organization_name"`
	IssuerOrganizationDomain string             `json:"issuer_organization_domain"`
	IssuerCountryCode        string             `json:"issuer_country_code"`
	ReplacedByPublicID       pgtype.Text        `json:"replaced_by_public_id"`
}

func (q *Queries) GetCertificateByPublicID(ctx context.Context, publicID string) (GetCertificateByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getCertificateByPublicID, publicID)
	var i GetCertificateByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Status,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GraduationDate,
		&i.IssueDate,
		&i.DocumentHash,
		&i.RevocationReasonCode,
		&i.RevokedAt,
		&i.RecipientName,
		&i.IssuerOrganizationName,
		&i.IssuerOrganizationDomain,
		&i.IssuerCountryCode,
		&i.ReplacedByPublicID,
	)
	return i, err
}

const issueCertificate = `-- name: IssueCertificate :one
UPDATE certificates
SET
    status = 'ISSUED',
    issued_by_user_id = $1,
    issued_at = NOW(),
    updated_at = NOW()
WHERE id = $2
  AND organization_id = $3
  AND status = 'DRAFT'
  AND issue_date <= CURRENT_DATE
  AND file_storage_key IS NOT NULL
  AND document_hash IS NOT NULL
  AND replaces_certificate_id IS NULL
  AND replaced_by_certificate_id IS NULL
  AND deleted_at IS NULL
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type IssueCertificateParams struct {
	IssuedByUserID pgtype.UUID `json:"issued_by_user_id"`
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) IssueCertificate(ctx context.Context, arg IssueCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, issueCertificate, arg.IssuedByUserID, arg.ID, arg.OrganizationID)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const issueReplacementCertificate = `-- name: IssueReplacementCertificate :one
UPDATE certificates
SET
    status = 'ISSUED',
    issued_by_user_id = $1,
    issued_at = NOW(),
    replaces_certificate_id = $2,
    updated_at = NOW()
WHERE id = $3
  AND organization_id = $4
  AND status = 'DRAFT'
  AND deleted_at IS NULL
  AND replaces_certificate_id IS NULL
  AND replaced_by_certificate_id IS NULL
  AND file_storage_key IS NOT NULL
  AND document_hash IS NOT NULL
  AND issue_date <= CURRENT_DATE
  AND id <> $2
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type IssueReplacementCertificateParams struct {
	IssuedByUserID        pgtype.UUID `json:"issued_by_user_id"`
	ReplacesCertificateID pgtype.UUID `json:"replaces_certificate_id"`
	ID                    pgtype.UUID `json:"id"`
	OrganizationID        pgtype.UUID `json:"organization_id"`
}

func (q *Queries) IssueReplacementCertificate(ctx context.Context, arg IssueReplacementCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, issueReplacementCertificate,
		arg.IssuedByUserID,
		arg.ReplacesCertificateID,
		arg.ID,
		arg.OrganizationID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const listCertificatesByOrganization = `-- name: ListCertificatesByOrganization :many
SELECT id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at FROM certificates
WHERE organization_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR recipient_email = LOWER($3))
  AND deleted_at IS NULL
ORDER BY created_at DESC, id ASC
LIMIT $5 OFFSET $4
`

type ListCertificatesByOrganizationParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Status         pgtype.Text `json:"status"`
	RecipientEmail pgtype.Text `json:"recipient_email"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

func (q *Queries) ListCertificatesByOrganization(ctx context.Context, arg ListCertificatesByOrganizationParams) ([]Certificate, error) {
	rows, err := q.db.Query(ctx, listCertificatesByOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.RecipientEmail,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Certificate
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.RecipientUserID,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.StudentIDNumber,
			&i.Title,
			&i.DegreeType,
			&i.Major,
			&i.GradeOrHonors,
			&i.GraduationDate,
			&i.IssueDate,
			&i.Status,
			&i.FileStorageKey,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.DocumentHash,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssuedByUserID,
			&i.IssuedAt,
			&i.RevokedByUserID,
			&i.RevokedAt,
			&i.RevocationReasonCode,
			&i.RevocationReason,
			&i.ReplacedByCertificateID,
			&i.ReplacesCertificateID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByRecipient = `-- name: ListCertificatesByRecipient :many
SELECT c.id, c.public_id, c.organization_id, c.recipient_user_id, c.recipient_name, c.recipient_email, c.student_id_number, c.title, c.degree_type, c.major, c.grade_or_honors, c.graduation_date, c.issue_date, c.status, c.file_storage_key, c.file_name, c.file_size, c.file_mime_type, c.document_hash, c.created_by_user_id, c.created_at, c.updated_at, c.issued_by_user_id, c.issued_at, c.revoked_by_user_id, c.revoked_at, c.revocation_reason_code, c.revocation_reason, c.replaced_by_certificate_id, c.replaces_certificate_id, c.deleted_at, o.legal_name AS organization_legal_name, o.official_domain AS organization_domain
FROM certificates c
JOIN organizations o ON o.id = c.organization_id
WHERE c.recipient_user_id = $1
  AND c.status IN ('ISSUED', 'REVOKED', 'REPLACED')
  AND ($2::text IS NULL OR c.status = $2)
  AND c.deleted_at IS NULL
  AND o.deleted_at IS NULL
ORDER BY c.issue_date DESC, c.id ASC
LIMIT $4 OFFSET $3
`

type ListCertificatesByRecipientParams struct {
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	Status          pgtype.Text `json:"status"`
	Offset          int32       `json:"offset"`
	Limit           int32       `json:"limit"`
}

type ListCertificatesByRecipientRow struct {
	ID                      pgtype.UUID        `json:"id"`
	PublicID                string             `json:"public_id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	RecipientUserID         pgtype.UUID        `json:"recipient_user_id"`
	RecipientName           string             `json:"recipient_name"`
	RecipientEmail          string             `json:"recipient_email"`
	StudentIDNumber         pgtype.Text        `json:"student_id_number"`
	Title                   string             `json:"title"`
	DegreeType              string             `json:"degree_type"`
	Major                   pgtype.Text        `json:"major"`
	GradeOrHonors           pgtype.Text        `json:"grade_or_honors"`
	GraduationDate          pgtype.Date        `json:"graduation_date"`
	IssueDate               pgtype.Date        `json:"issue_date"`
	Status                  string             `json:"status"`
	FileStorageKey          pgtype.Text        `json:"file_storage_key"`
	FileName                pgtype.Text        `json:"file_name"`
	FileSize                pgtype.Int8        `json:"file_size"`
	FileMimeType            pgtype.Text        `json:"file_mime_type"`
	DocumentHash            pgtype.Text        `json:"document_hash"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	IssuedByUserID          pgtype.UUID        `json:"issued_by_user_id"`
	IssuedAt                pgtype.Timestamptz `json:"issued_at"`
	RevokedByUserID         pgtype.UUID        `json:"revoked_by_user_id"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	RevocationReasonCode    pgtype.Text        `json:"revocation_reason_code"`
	RevocationReason        pgtype.Text        `json:"revocation_reason"`
	ReplacedByCertificateID pgtype.UUID        `json:"replaced_by_certificate_id"`
	ReplacesCertificateID   pgtype.UUID        `json:"replaces_certificate_id"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	OrganizationLegalName   string             `json:"organization_legal_name"`
	OrganizationDomain      string             `json:"organization_domain"`
}

func (q *Queries) ListCertificatesByRecipient(ctx context.Context, arg ListCertificatesByRecipientParams) ([]ListCertificatesByRecipientRow, error) {
	rows, err := q.db.Query(ctx, listCertificatesByRecipient,
		arg.RecipientUserID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCertificatesByRecipientRow
	for rows.Next() {
		var i ListCertificatesByRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrganizationID,
			&i.RecipientUserID,
			&i.RecipientName,
			&i.RecipientEmail,
			&i.StudentIDNumber,
			&i.Title,
			&i.DegreeType,
			&i.Major,
			&i.GradeOrHonors,
			&i.GraduationDate,
			&i.IssueDate,
			&i.Status,
			&i.FileStorageKey,
			&i.FileName,
			&i.FileSize,
			&i.FileMimeType,
			&i.DocumentHash,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssuedByUserID,
			&i.IssuedAt,
			&i.RevokedByUserID,
			&i.RevokedAt,
			&i.RevocationReasonCode,
			&i.RevocationReason,
			&i.ReplacedByCertificateID,
			&i.ReplacesCertificateID,
			&i.DeletedAt,
			&i.OrganizationLegalName,
			&i.OrganizationDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCertificateReplaced = `-- name: MarkCertificateReplaced :one
UPDATE certificates
SET
    status = 'REPLACED',
    revoked_by_user_id = $1,
    revoked_at = NOW(),
    revocation_reason_code = $2,
    revocation_reason = $3,
    replaced_by_certificate_id = $4,
    updated_at = NOW()
WHERE id = $5
  AND organization_id = $6
  AND status = 'ISSUED'
  AND replaced_by_certificate_id IS NULL
  AND deleted_at IS NULL
  AND id <> $4
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type MarkCertificateReplacedParams struct {
	RevokedByUserID         pgtype.UUID `json:"revoked_by_user_id"`
	RevocationReasonCode    pgtype.Text `json:"revocation_reason_code"`
	RevocationReason        pgtype.Text `json:"revocation_reason"`
	ReplacedByCertificateID pgtype.UUID `json:"replaced_by_certificate_id"`
	ID                      pgtype.UUID `json:"id"`
	OrganizationID          pgtype.UUID `json:"organization_id"`
}

func (q *Queries) MarkCertificateReplaced(ctx context.Context, arg MarkCertificateReplacedParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, markCertificateReplaced,
		arg.RevokedByUserID,
		arg.RevocationReasonCode,
		arg.RevocationReason,
		arg.ReplacedByCertificateID,
		arg.ID,
		arg.OrganizationID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const revokeCertificate = `-- name: RevokeCertificate :one
UPDATE certificates
SET
    status = 'REVOKED',
    revoked_by_user_id = $1,
    revoked_at = NOW(),
    revocation_reason_code = $2,
    revocation_reason = $3,
    updated_at = NOW()
WHERE id = $4
  AND organization_id = $5
  AND status = 'ISSUED'
  AND deleted_at IS NULL
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type RevokeCertificateParams struct {
	RevokedByUserID      pgtype.UUID `json:"revoked_by_user_id"`
	RevocationReasonCode pgtype.Text `json:"revocation_reason_code"`
	RevocationReason     pgtype.Text `json:"revocation_reason"`
	ID                   pgtype.UUID `json:"id"`
	OrganizationID       pgtype.UUID `json:"organization_id"`
}

func (q *Queries) RevokeCertificate(ctx context.Context, arg RevokeCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, revokeCertificate,
		arg.RevokedByUserID,
		arg.RevocationReasonCode,
		arg.RevocationReason,
		arg.ID,
		arg.OrganizationID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}

const updateCertificateDraft = `-- name: UpdateCertificateDraft :one
UPDATE certificates
SET
    recipient_user_id = COALESCE($1, recipient_user_id),
    recipient_name = COALESCE($2, recipient_name),
    recipient_email = COALESCE($3, recipient_email),
    student_id_number = COALESCE($4, student_id_number),
    title = COALESCE($5, title),
    degree_type = COALESCE($6, degree_type),
    major = COALESCE($7, major),
    grade_or_honors = COALESCE($8, grade_or_honors),
    graduation_date = COALESCE($9, graduation_date),
    issue_date = COALESCE($10, issue_date),
    updated_at = NOW()
WHERE id = $11
  AND organization_id = $12
  AND status = 'DRAFT'
  AND deleted_at IS NULL
RETURNING id, public_id, organization_id, recipient_user_id, recipient_name, recipient_email, student_id_number, title, degree_type, major, grade_or_honors, graduation_date, issue_date, status, file_storage_key, file_name, file_size, file_mime_type, document_hash, created_by_user_id, created_at, updated_at, issued_by_user_id, issued_at, revoked_by_user_id, revoked_at, revocation_reason_code, revocation_reason, replaced_by_certificate_id, replaces_certificate_id, deleted_at
`

type UpdateCertificateDraftParams struct {
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	RecipientName   pgtype.Text `json:"recipient_name"`
	RecipientEmail  pgtype.Text `json:"recipient_email"`
	StudentIDNumber pgtype.Text `json:"student_id_number"`
	Title           pgtype.Text `json:"title"`
	DegreeType      pgtype.Text `json:"degree_type"`
	Major           pgtype.Text `json:"major"`
	GradeOrHonors   pgtype.Text `json:"grade_or_honors"`
	GraduationDate  pgtype.Date `json:"graduation_date"`
	IssueDate       pgtype.Date `json:"issue_date"`
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdateCertificateDraft(ctx context.Context, arg UpdateCertificateDraftParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, updateCertificateDraft,
		arg.RecipientUserID,
		arg.RecipientName,
		arg.RecipientEmail,
		arg.StudentIDNumber,
		arg.Title,
		arg.DegreeType,
		arg.Major,
		arg.GradeOrHonors,
		arg.GraduationDate,
		arg.IssueDate,
		arg.ID,
		arg.OrganizationID,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrganizationID,
		&i.RecipientUserID,
		&i.RecipientName,
		&i.RecipientEmail,
		&i.StudentIDNumber,
		&i.Title,
		&i.DegreeType,
		&i.Major,
		&i.GradeOrHonors,
		&i.GraduationDate,
		&i.IssueDate,
		&i.Status,
		&i.FileStorageKey,
		&i.FileName,
		&i.FileSize,
		&i.FileMimeType,
		&i.DocumentHash,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.RevokedByUserID,
		&i.RevokedAt,
		&i.RevocationReasonCode,
		&i.RevocationReason,
		&i.ReplacedByCertificateID,
		&i.ReplacesCertificateID,
		&i.DeletedAt,
	)
	return i, err
}
