// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (
    organization_id, user_id, role, is_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, organization_id, user_id, role, is_active, created_at, updated_at
`

type CreateMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.IsActive,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, organization_id, user_id, role, is_active, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipsByOrgID = `-- name: ListMembershipsByOrgID :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.is_active, om.created_at, om.updated_at,
       u.email AS user_email, u.full_name AS user_full_name
FROM organization_memberships om
JOIN users u ON u.id = om.user_id
WHERE om.organization_id = $1 AND u.deleted_at IS NULL
ORDER BY om.created_at ASC
`

type ListMembershipsByOrgIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserEmail      string             `json:"user_email"`
	UserFullName   string             `json:"user_full_name"`
}

func (q *Queries) ListMembershipsByOrgID(ctx context.Context, organizationID pgtype.UUID) ([]ListMembershipsByOrgIDRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrgID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByOrgIDRow
	for rows.Next() {
		var i ListMembershipsByOrgIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
			&i.UserFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUserID = `-- name: ListMembershipsByUserID :many
SELECT om.id, om.organization_id, om.user_id, om.role, om.is_active, om.created_at, om.updated_at,
       o.legal_name AS organization_legal_name, o.org_type AS organization_type, o.verification_status AS organization_status
FROM organization_memberships om
JOIN organizations o ON o.id = om.organization_id
WHERE om.user_id = $1 AND om.is_active = TRUE AND o.deleted_at IS NULL
ORDER BY om.created_at ASC
`

type ListMembershipsByUserIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	OrganizationID        pgtype.UUID        `json:"organization_id"`
	UserID                pgtype.UUID        `json:"user_id"`
	Role                  string             `json:"role"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	OrganizationLegalName string             `json:"organization_legal_name"`
	OrganizationType      string             `json:"organization_type"`
	OrganizationStatus    string             `json:"organization_status"`
}

func (q *Queries) ListMembershipsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListMembershipsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserIDRow
	for rows.Next() {
		var i ListMembershipsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationLegalName,
			&i.OrganizationType,
			&i.OrganizationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE organization_memberships
SET
    role = $3,
    is_active = $4,
    updated_at = NOW()
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, is_active, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Role           string      `json:"role"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.IsActive,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
