// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID                   pgtype.UUID        `json:"id"`
	ActorUserID          pgtype.UUID        `json:"actor_user_id"`
	TargetOrganizationID pgtype.UUID        `json:"target_organization_id"`
	Action               string             `json:"action"`
	ResourceType         string             `json:"resource_type"`
	ResourceID           pgtype.UUID        `json:"resource_id"`
	Payload              []byte             `json:"payload"`
	IpAddress            *netip.Addr        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AuthIdentity struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	IdentityType   string             `json:"identity_type"`
	Identifier     string             `json:"identifier"`
	CredentialHash pgtype.Text        `json:"credential_hash"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Certificate struct {
	ID                      pgtype.UUID        `json:"id"`
	PublicID                string             `json:"public_id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	RecipientUserID         pgtype.UUID        `json:"recipient_user_id"`
	RecipientName           string             `json:"recipient_name"`
	RecipientEmail          string             `json:"recipient_email"`
	StudentIDNumber         pgtype.Text        `json:"student_id_number"`
	Title                   string             `json:"title"`
	DegreeType              string             `json:"degree_type"`
	Major                   pgtype.Text        `json:"major"`
	GradeOrHonors           pgtype.Text        `json:"grade_or_honors"`
	GraduationDate          pgtype.Date        `json:"graduation_date"`
	IssueDate               pgtype.Date        `json:"issue_date"`
	Status                  string             `json:"status"`
	FileStorageKey          pgtype.Text        `json:"file_storage_key"`
	FileName                pgtype.Text        `json:"file_name"`
	FileSize                pgtype.Int8        `json:"file_size"`
	FileMimeType            pgtype.Text        `json:"file_mime_type"`
	DocumentHash            pgtype.Text        `json:"document_hash"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	IssuedByUserID          pgtype.UUID        `json:"issued_by_user_id"`
	IssuedAt                pgtype.Timestamptz `json:"issued_at"`
	RevokedByUserID         pgtype.UUID        `json:"revoked_by_user_id"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	RevocationReasonCode    pgtype.Text        `json:"revocation_reason_code"`
	RevocationReason        pgtype.Text        `json:"revocation_reason"`
	ReplacedByCertificateID pgtype.UUID        `json:"replaced_by_certificate_id"`
	ReplacesCertificateID   pgtype.UUID        `json:"replaces_certificate_id"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type Organization struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgType            string             `json:"org_type"`
	LegalName          string             `json:"legal_name"`
	TradeName          pgtype.Text        `json:"trade_name"`
	CountryCode        string             `json:"country_code"`
	RegistrationNumber string             `json:"registration_number"`
	OfficialDomain     string             `json:"official_domain"`
	VerificationStatus string             `json:"verification_status"`
	ReviewedByUserID   pgtype.UUID        `json:"reviewed_by_user_id"`
	ReviewedAt         pgtype.Timestamptz `json:"reviewed_at"`
	DecisionReason     pgtype.Text        `json:"decision_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type OrganizationMembership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	FullName      string             `json:"full_name"`
	IsActive      bool               `json:"is_active"`
	IsSuperadmin  bool               `json:"is_superadmin"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
