// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID                   pgtype.UUID        `json:"id"`
	ActorUserID          pgtype.UUID        `json:"actor_user_id"`
	TargetOrganizationID pgtype.UUID        `json:"target_organization_id"`
	Action               string             `json:"action"`
	ResourceType         string             `json:"resource_type"`
	ResourceID           pgtype.UUID        `json:"resource_id"`
	Payload              []byte             `json:"payload"`
	IpAddress            *netip.Addr        `json:"ip_address"`
	UserAgent            pgtype.Text        `json:"user_agent"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type AuthIdentity struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	IdentityType   string             `json:"identity_type"`
	Identifier     string             `json:"identifier"`
	CredentialHash pgtype.Text        `json:"credential_hash"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BatchCertificate struct {
	ID            pgtype.UUID        `json:"id"`
	BatchID       pgtype.UUID        `json:"batch_id"`
	CertificateID pgtype.UUID        `json:"certificate_id"`
	LeafIndex     int32              `json:"leaf_index"`
	LeafHash      string             `json:"leaf_hash"`
	ProofDepth    int32              `json:"proof_depth"`
	PublicID      string             `json:"public_id"`
	DocumentHash  string             `json:"document_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type BatchCertificateProofNode struct {
	ID                 pgtype.UUID        `json:"id"`
	BatchCertificateID pgtype.UUID        `json:"batch_certificate_id"`
	ProofIndex         int32              `json:"proof_index"`
	SiblingHash        string             `json:"sibling_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type BlockchainTransaction struct {
	ID                      pgtype.UUID        `json:"id"`
	BatchID                 pgtype.UUID        `json:"batch_id"`
	NonceReservationID      pgtype.UUID        `json:"nonce_reservation_id"`
	ReplacementSequence     int32              `json:"replacement_sequence"`
	ChainID                 int64              `json:"chain_id"`
	FromAddress             string             `json:"from_address"`
	ToAddress               string             `json:"to_address"`
	Nonce                   int64              `json:"nonce"`
	TransactionType         int32              `json:"transaction_type"`
	ValueWei                pgtype.Numeric     `json:"value_wei"`
	Calldata                []byte             `json:"calldata"`
	GasLimit                int64              `json:"gas_limit"`
	MaxFeePerGasWei         pgtype.Numeric     `json:"max_fee_per_gas_wei"`
	MaxPriorityFeePerGasWei pgtype.Numeric     `json:"max_priority_fee_per_gas_wei"`
	TxHash                  string             `json:"tx_hash"`
	Status                  string             `json:"status"`
	BlockNumber             pgtype.Int8        `json:"block_number"`
	BlockHash               pgtype.Text        `json:"block_hash"`
	GasUsed                 pgtype.Int8        `json:"gas_used"`
	ReplacesTransactionID   pgtype.UUID        `json:"replaces_transaction_id"`
	FailureCode             pgtype.Text        `json:"failure_code"`
	FailureDetailCode       pgtype.Text        `json:"failure_detail_code"`
	PreparedAt              pgtype.Timestamptz `json:"prepared_at"`
	BroadcastAt             pgtype.Timestamptz `json:"broadcast_at"`
	MinedAt                 pgtype.Timestamptz `json:"mined_at"`
	ReplacedAt              pgtype.Timestamptz `json:"replaced_at"`
	FailedAt                pgtype.Timestamptz `json:"failed_at"`
}

type Certificate struct {
	ID                      pgtype.UUID        `json:"id"`
	PublicID                string             `json:"public_id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	RecipientUserID         pgtype.UUID        `json:"recipient_user_id"`
	RecipientName           string             `json:"recipient_name"`
	RecipientEmail          string             `json:"recipient_email"`
	StudentIDNumber         pgtype.Text        `json:"student_id_number"`
	Title                   string             `json:"title"`
	DegreeType              string             `json:"degree_type"`
	Major                   pgtype.Text        `json:"major"`
	GradeOrHonors           pgtype.Text        `json:"grade_or_honors"`
	GraduationDate          pgtype.Date        `json:"graduation_date"`
	IssueDate               pgtype.Date        `json:"issue_date"`
	Status                  string             `json:"status"`
	FileStorageKey          pgtype.Text        `json:"file_storage_key"`
	FileName                pgtype.Text        `json:"file_name"`
	FileSize                pgtype.Int8        `json:"file_size"`
	FileMimeType            pgtype.Text        `json:"file_mime_type"`
	DocumentHash            pgtype.Text        `json:"document_hash"`
	CreatedByUserID         pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	IssuedByUserID          pgtype.UUID        `json:"issued_by_user_id"`
	IssuedAt                pgtype.Timestamptz `json:"issued_at"`
	RevokedByUserID         pgtype.UUID        `json:"revoked_by_user_id"`
	RevokedAt               pgtype.Timestamptz `json:"revoked_at"`
	RevocationReasonCode    pgtype.Text        `json:"revocation_reason_code"`
	RevocationReason        pgtype.Text        `json:"revocation_reason"`
	ReplacedByCertificateID pgtype.UUID        `json:"replaced_by_certificate_id"`
	ReplacesCertificateID   pgtype.UUID        `json:"replaces_certificate_id"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
}

type MerkleBatch struct {
	ID                         pgtype.UUID        `json:"id"`
	BatchNumber                int64              `json:"batch_number"`
	CanonicalBatchID           string             `json:"canonical_batch_id"`
	Status                     string             `json:"status"`
	TreeAlgorithm              string             `json:"tree_algorithm"`
	TreeVersion                int32              `json:"tree_version"`
	LeafEncodingVersion        string             `json:"leaf_encoding_version"`
	ProofFormatVersion         string             `json:"proof_format_version"`
	MerkleRoot                 pgtype.Text        `json:"merkle_root"`
	LeafCount                  int32              `json:"leaf_count"`
	ClaimedBy                  pgtype.Text        `json:"claimed_by"`
	ClaimExpiresAt             pgtype.Timestamptz `json:"claim_expires_at"`
	AuthoritativeTransactionID pgtype.UUID        `json:"authoritative_transaction_id"`
	ChainID                    pgtype.Int8        `json:"chain_id"`
	ContractAddress            pgtype.Text        `json:"contract_address"`
	BlockNumber                pgtype.Int8        `json:"block_number"`
	BlockHash                  pgtype.Text        `json:"block_hash"`
	ConfirmationCount          int32              `json:"confirmation_count"`
	RetryCount                 int32              `json:"retry_count"`
	FailureStage               pgtype.Text        `json:"failure_stage"`
	FailureCode                pgtype.Text        `json:"failure_code"`
	FailureDetailCode          pgtype.Text        `json:"failure_detail_code"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ReadyAt                    pgtype.Timestamptz `json:"ready_at"`
	SubmittedAt                pgtype.Timestamptz `json:"submitted_at"`
	ConfirmedAt                pgtype.Timestamptz `json:"confirmed_at"`
	FailedAt                   pgtype.Timestamptz `json:"failed_at"`
}

type Organization struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgType            string             `json:"org_type"`
	LegalName          string             `json:"legal_name"`
	TradeName          pgtype.Text        `json:"trade_name"`
	CountryCode        string             `json:"country_code"`
	RegistrationNumber string             `json:"registration_number"`
	OfficialDomain     string             `json:"official_domain"`
	VerificationStatus string             `json:"verification_status"`
	ReviewedByUserID   pgtype.UUID        `json:"reviewed_by_user_id"`
	ReviewedAt         pgtype.Timestamptz `json:"reviewed_at"`
	DecisionReason     pgtype.Text        `json:"decision_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type OrganizationMembership struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SignerNonceReservation struct {
	ID            pgtype.UUID        `json:"id"`
	BatchID       pgtype.UUID        `json:"batch_id"`
	ChainID       int64              `json:"chain_id"`
	SignerAddress string             `json:"signer_address"`
	Nonce         int64              `json:"nonce"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CommittedAt   pgtype.Timestamptz `json:"committed_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	FullName      string             `json:"full_name"`
	IsActive      bool               `json:"is_active"`
	IsSuperadmin  bool               `json:"is_superadmin"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
