// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    org_type, legal_name, trade_name, country_code, registration_number, official_domain, verification_status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'PENDING'
)
RETURNING id, org_type, legal_name, trade_name, country_code, registration_number, official_domain, verification_status, reviewed_by_user_id, reviewed_at, decision_reason, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	OrgType            string      `json:"org_type"`
	LegalName          string      `json:"legal_name"`
	TradeName          pgtype.Text `json:"trade_name"`
	CountryCode        string      `json:"country_code"`
	RegistrationNumber string      `json:"registration_number"`
	OfficialDomain     string      `json:"official_domain"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.OrgType,
		arg.LegalName,
		arg.TradeName,
		arg.CountryCode,
		arg.RegistrationNumber,
		arg.OfficialDomain,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.OrgType,
		&i.LegalName,
		&i.TradeName,
		&i.CountryCode,
		&i.RegistrationNumber,
		&i.OfficialDomain,
		&i.VerificationStatus,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByDomain = `-- name: GetOrganizationByDomain :one
SELECT id, org_type, legal_name, trade_name, country_code, registration_number, official_domain, verification_status, reviewed_by_user_id, reviewed_at, decision_reason, created_at, updated_at, deleted_at
FROM organizations
WHERE LOWER(official_domain) = LOWER($1) AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByDomain(ctx context.Context, lower string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByDomain, lower)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.OrgType,
		&i.LegalName,
		&i.TradeName,
		&i.CountryCode,
		&i.RegistrationNumber,
		&i.OfficialDomain,
		&i.VerificationStatus,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, org_type, legal_name, trade_name, country_code, registration_number, official_domain, verification_status, reviewed_by_user_id, reviewed_at, decision_reason, created_at, updated_at, deleted_at
FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.OrgType,
		&i.LegalName,
		&i.TradeName,
		&i.CountryCode,
		&i.RegistrationNumber,
		&i.OfficialDomain,
		&i.VerificationStatus,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrganizationsByStatus = `-- name: ListOrganizationsByStatus :many
SELECT id, org_type, legal_name, trade_name, country_code, registration_number, official_domain, verification_status, reviewed_by_user_id, reviewed_at, decision_reason, created_at, updated_at, deleted_at
FROM organizations
WHERE verification_status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizationsByStatus(ctx context.Context, verificationStatus string) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByStatus, verificationStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.OrgType,
			&i.LegalName,
			&i.TradeName,
			&i.CountryCode,
			&i.RegistrationNumber,
			&i.OfficialDomain,
			&i.VerificationStatus,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.DecisionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewOrganization = `-- name: ReviewOrganization :one
UPDATE organizations
SET
    verification_status = $2,
    reviewed_by_user_id = $3,
    reviewed_at = NOW(),
    decision_reason = $4,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_type, legal_name, trade_name, country_code, registration_number, official_domain, verification_status, reviewed_by_user_id, reviewed_at, decision_reason, created_at, updated_at, deleted_at
`

type ReviewOrganizationParams struct {
	ID                 pgtype.UUID `json:"id"`
	VerificationStatus string      `json:"verification_status"`
	ReviewedByUserID   pgtype.UUID `json:"reviewed_by_user_id"`
	DecisionReason     pgtype.Text `json:"decision_reason"`
}

func (q *Queries) ReviewOrganization(ctx context.Context, arg ReviewOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, reviewOrganization,
		arg.ID,
		arg.VerificationStatus,
		arg.ReviewedByUserID,
		arg.DecisionReason,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.OrgType,
		&i.LegalName,
		&i.TradeName,
		&i.CountryCode,
		&i.RegistrationNumber,
		&i.OfficialDomain,
		&i.VerificationStatus,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.DecisionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, id)
	return err
}
